import { useEffect,useState } from 'react';
import { useFamily } from './family-context';
import { learningCloud } from './cloud';
import PairingCode from './PairingCode';
export default function ConnectParent(){
 const family=useFamily();const own=family.profiles.find(p=>p.access==='self');
 const [invite,setInvite]=useState<{code:string;expires_at:string}|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [requests,setRequests]=useState<{id:string;requested_by:string|null}[]>([]);
 useEffect(()=>{if(!own)return;let alive=true;const load=async()=>{const {data}=await learningCloud.from('learner_invites').select('*').eq('learner_id',own.id).eq('purpose','guardian').not('requested_by','is',null).is('approved_at',null).is('revoked_at',null);if(alive)setRequests(data||[]);};void load();const timer=window.setInterval(()=>void load(),10000);return()=>{alive=false;window.clearInterval(timer);};},[own]);
 const perform=async(work:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await work();}catch(e){setMessage((e as {message?:string})?.message||'Propojení se nezdařilo.');}finally{setBusy(false);}};
 if(!own)return null;
 return <section className="learn-panel"><h2>Propojit tento profil s rodičem</h2><p>Jsi přihlášený/á ve svém účtu a chceš, aby rodič viděl tvoje výsledky? Vytvoř kód a předej mu jej. Tvůj slovník a výsledky zůstanou zachované.</p><button className="learn-button secondary" disabled={busy} onClick={()=>void perform(async()=>{const {data,error}=await learningCloud.rpc('issue_learner_invite',{p_learner_id:own.id,p_purpose:'guardian'});if(error)throw error;setInvite(data as unknown as {code:string;expires_at:string});})}>{busy?'Chvilku strpení…':'Vytvořit kód pro rodiče'}</button>{invite&&<><PairingCode key={invite.code} code={invite.code} expires={invite.expires_at}/><p>Rodič ve svém účtu otevře „Moje děti → Dítě již má vlastní účet“ a vloží kód. Potom zde jeho žádost potvrdíš.</p></>}{requests.map(request=><div key={request.id} className="learn-notice"><span>Účet žádá rodičovský přístup k tvým výsledkům. Potvrď jen svého rodiče.</span>{[true,false].map(approve=><button key={String(approve)} disabled={busy} onClick={()=>void perform(async()=>{const {error}=await learningCloud.rpc('approve_learner_access',{p_invite_id:request.id,p_approve:approve});if(error)throw error;setRequests(previous=>previous.filter(r=>r.id!==request.id));setMessage(approve?'Rodič byl připojen.':'Žádost byla odmítnuta.');})}>{approve?'Povolit rodiči':'Odmítnout'}</button>)}</div>)}{message&&<p role="status">{message}</p>}</section>;
}
