import { useEffect,useState } from 'react';
import { useFamily } from './family-context';
import { learningCloud } from './cloud';
export default function ConnectParent(){
 const family=useFamily();const own=family.profiles.find(p=>p.access==='self');
 const [code,setCode]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [requests,setRequests]=useState<{id:string;requested_by:string|null}[]>([]);
 useEffect(()=>{if(!own)return;let alive=true;const load=async()=>{const {data}=await learningCloud.from('learner_invites').select('*').eq('learner_id',own.id).eq('purpose','guardian').not('requested_by','is',null).is('approved_at',null).is('revoked_at',null);if(alive)setRequests(data||[]);};void load();const timer=window.setInterval(()=>void load(),10000);return()=>{alive=false;window.clearInterval(timer);};},[own]);
 const perform=async(work:()=>Promise<void>)=>{setBusy(true);try{await work();}catch(e){setMessage((e as {message?:string})?.message||'Propojení se nezdařilo.');}finally{setBusy(false);}};
 if(!own)return null;
 return <details className="learn-panel"><summary>Propojit tento profil s rodičem</summary><p>Pokud už máš vlastní výsledky, rodič může připojit právě tento profil. Nevytváří se nový slovník ani kopie výsledků.</p><button className="learn-button secondary" disabled={busy} onClick={()=>void perform(async()=>{const {data,error}=await learningCloud.rpc('issue_learner_invite',{p_learner_id:own.id,p_purpose:'guardian'});if(error)throw error;setCode((data as unknown as {code:string}).code);})}>Vytvořit kód pro rodiče</button>{code&&<><strong className="family-code">{code}</strong><p>Rodič zadá kód v „Moje děti → Dítě již má vlastní účet“. Kód platí 10 minut. Přístup k výsledkům udělíš až potvrzením žádosti zde.</p></>}{requests.map(request=><div key={request.id} className="learn-notice"><span>Účet žádá rodičovský přístup k tvým výsledkům. Potvrď jen svého rodiče.</span>{[true,false].map(approve=><button key={String(approve)} disabled={busy} onClick={()=>void perform(async()=>{const {error}=await learningCloud.rpc('approve_learner_access',{p_invite_id:request.id,p_approve:approve});if(error)throw error;setRequests(previous=>previous.filter(r=>r.id!==request.id));setMessage(approve?'Rodič byl připojen.':'Žádost byla odmítnuta.');})}>{approve?'Povolit rodiči':'Odmítnout'}</button>)}</div>)}{message&&<p role="status">{message}</p>}</details>;
}
