import { useMemo, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Pencil, Plus, Download, Upload, Search } from 'lucide-react';
import { useLearning } from './context';
import { dictionaryWords, dictionaryCsv, filterWords, parseDictionaryCsv, translationVariants } from './dictionary';
import { downloadText } from './storage';
import type { LearningWord, Source } from './types';
export default function DictionaryManager() {
  const {data,saveWords}=useLearning(); const [source,setSource]=useState<Source>('personal'); const [query,setQuery]=useState(''); const [edit,setEdit]=useState<LearningWord|null>(null); const [preview,setPreview]=useState<Array<{english:string;czech:string}>>([]); const [message,setMessage]=useState(''); const upload=useRef<HTMLInputElement>(null);
  const words=useMemo(()=>dictionaryWords(data.words),[data.words]); const selected=filterWords(words,source).filter(w=>`${w.english} ${w.czech} ${w.category}`.toLocaleLowerCase('cs').includes(query.toLocaleLowerCase('cs')));
  const save=()=>{if(!edit)return;try{saveWords([{...edit,accepted:translationVariants(edit.czech)}]);setEdit(null);setMessage('Slovíčko je uložené.');}catch(error){setMessage(error instanceof Error?error.message:'Slovíčko se nepodařilo uložit.');}};
  return <><Link className="learn-back" to="/dictionary"><ArrowLeft size={18}/> Zpět na procvičování</Link><div className="learn-page-heading"><div><p className="learn-eyebrow">Všechna tvoje slova na jednom místě</p><h1>Slovník</h1><p>{filterWords(words,'personal').length} osobních a {filterWords(words,'school').length} školních slovíček.</p></div><button className="learn-button primary" onClick={()=>setEdit({id:crypto.randomUUID(),english:'',czech:'',accepted:[],source:'personal',category:'Můj slovník'})}><Plus size={18}/> Přidat slovíčko</button></div><div className="dictionary-toolbar"><fieldset className="learn-chips"><legend className="sr-only">Zdroj slovíček</legend>{([{id:'personal',label:'Můj slovník'},{id:'school',label:'Školní'},{id:'all',label:'Všechna'}] as {id:Source;label:string}[]).map(s=><button key={s.id} aria-pressed={source===s.id} className={source===s.id?'selected':''} onClick={()=>setSource(s.id)}>{s.label}</button>)}</fieldset><label className="dictionary-search"><Search size={18}/><span className="sr-only">Hledat ve slovníku</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Hledat slovo nebo překlad"/></label></div><div className="learn-actions"><button className="learn-button secondary" onClick={()=>downloadText('procvicka-slovnik.csv',dictionaryCsv(filterWords(words,source)),'text/csv;charset=utf-8')}><Download size={18}/> Export CSV</button><button className="learn-button secondary" onClick={()=>upload.current?.click()}><Upload size={18}/> Import osobních slov</button><input ref={upload} type="file" accept=".csv,text/csv" aria-label="CSV slovníku" className="sr-only" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>2_000_000)throw new Error('Soubor je příliš velký (maximum 2 MB).');const rows=parseDictionaryCsv(await file.text());if(rows.length>5000)throw new Error('Importuj nejvýše 5000 slov najednou.');setPreview(rows);setMessage('');}catch(error){setMessage(error instanceof Error?error.message:'CSV se nepodařilo načíst.');}e.target.value='';}}/></div>{message&&<p className="learn-notice" role="status">{message}</p>}
    {edit&&<form className="learn-panel learn-stack" onSubmit={e=>{e.preventDefault();save();}}><h2>{words.some(w=>w.id===edit.id)?'Upravit slovíčko':'Nové slovíčko'}</h2><div className="learn-form-grid"><label>Anglicky<input autoFocus value={edit.english} onChange={e=>setEdit({...edit,english:e.target.value})} maxLength={200} required/></label><label>Česky · varianty odděl středníkem<input value={edit.czech} onChange={e=>setEdit({...edit,czech:e.target.value})} maxLength={500} required/></label></div><div className="learn-actions"><button className="learn-button primary" type="submit">Uložit slovíčko</button><button className="learn-button secondary" type="button" onClick={()=>setEdit(null)}>Zrušit</button></div></form>}
    {preview.length>0&&<section className="learn-panel"><h2>Import: {preview.length} slovíček</h2><p>Slova se stejným anglickým zněním aktualizují překlad v osobním slovníku. Ostatní slova zůstanou zachovaná.</p>{preview.slice(0,5).map((w,i)=><p key={i}>{w.english} → {w.czech}</p>)}<div className="learn-actions"><button className="learn-button primary" onClick={()=>{saveWords(preview.map(w=>({...w,id:words.find(existing=>existing.source==='personal'&&existing.english.toLocaleLowerCase('en')===w.english.toLocaleLowerCase('en'))?.id||crypto.randomUUID(),accepted:translationVariants(w.czech),source:'personal',category:'Můj slovník'})));setMessage(`Importováno ${preview.length} slovíček.`);setPreview([]);}}>Potvrdit import</button><button className="learn-button secondary" onClick={()=>setPreview([])}>Zrušit</button></div></section>}
    <p className="learn-muted">Zobrazeno {selected.length} slovíček. Školní sadu spravuje aplikace.</p><div className="learn-word-list">{selected.map(w=><article key={w.id}><div><h2>{w.english}</h2><p>{w.czech}</p><small>{w.source==='personal'?'Můj slovník':w.category}</small></div>{w.source==='personal'&&<button className="learn-icon-button" onClick={()=>setEdit({...w})} aria-label={`Upravit ${w.english}`}><Pencil size={19}/></button>}</article>)}</div>{!selected.length&&<div className="learn-panel"><h2>Takové slovíčko tu ještě není.</h2><p>Zkus jiné hledání nebo přidej vlastní slovo.</p></div>}
  </>;
}
