import { describe,it,expect,beforeEach } from 'vitest';
import { mathPool,selectTasks } from './math';
import { spellingTasks,spellingGroupNames } from './spelling';
import { dictionaryWords,personalWords,schoolWords,englishTask,dictionaryCsv,parseDictionaryCsv } from './dictionary';
import { isCorrect,reduceLesson,summarize } from './session';
import { calendarDay,levelProgress,lessonXp,streak,rebuildReviews } from './rewards';
import { newBadges } from './badges';
import { parseLearningData,emptyLearningData,readLearningData,storageKey,mergeSessions } from './storage';
import type { LessonSession,Task } from './types';
const at='2026-10-04T10:00:00.000Z';
const make=(count=5):LessonSession=>({id:'lesson',learnerId:'gabi',subject:'math',contentVersion:'learning-v2',title:'Sčítání do 10',mode:'typing',tasks:mathPool({operations:['+'],min:1,max:10,factorMin:1,factorMax:10}).slice(0,count).map((t,i)=>({...t,id:`task-${i}`})),attempts:[],index:0,phase:'answering',revealed:false,usedHint:false,status:'active',startedAt:at,xp:0,sync:'local'});
const answer=(s:LessonSession,value=s.tasks[s.index].expected[0])=>reduceLesson(s,{type:'answer',answer:value,id:`attempt-${s.attempts.length}`,at});
const complete=(s=make())=>{for(let i=0;i<s.tasks.length;i++){s=answer(s);s=reduceLesson(s,{type:'next',at});}return {...s,activityDate:'2026-10-04'};};
describe('mathematics within the declared bounds',()=>{
  for(const max of [10,20,100])it(`respects addition and subtraction to ${max}`,()=>{const pool=mathPool({operations:['+','-'],min:1,max,factorMin:0,factorMax:12});for(const t of pool){expect(t.a).toBeGreaterThanOrEqual(1);expect(t.b).toBeGreaterThanOrEqual(1);expect(t.result).toBeGreaterThanOrEqual(0);expect(t.result).toBeLessThanOrEqual(max);expect(t.result).toBe(t.operation==='+'?t.a+t.b:t.a-t.b);}});
  it('uses integer division and never divides by zero',()=>{for(const t of mathPool({operations:['*','/'],min:1,max:10,factorMin:0,factorMax:12})){expect(Number.isInteger(t.result)).toBe(true);if(t.operation==='/'){expect(t.b).toBeGreaterThan(0);expect(t.result*t.b).toBe(t.a);}else expect(t.result).toBe(t.a*t.b);}});
  it('rejects impossible bounds and finishes an exhausted one-item pool',()=>{expect(()=>mathPool({operations:['+'],min:1,max:1,factorMin:1,factorMax:10})).toThrow();const pool=mathPool({operations:['+'],min:5,max:10,factorMin:1,factorMax:10});expect(pool).toHaveLength(1);expect(selectTasks(pool,20)).toHaveLength(20);expect(selectTasks(pool,20).every(t=>t.a===5&&t.b===5&&t.result===10)).toBe(true);});
  it('rejects empty selections, decimals and invalid ranges',()=>{for(const options of [{operations:[]},{min:1.5},{max:101},{factorMin:13},{factorMax:0,operations:['/']}])expect(()=>mathPool({operations:['+'],min:1,max:10,factorMin:1,factorMax:10,...options} as Parameters<typeof mathPool>[0])).toThrow();});
  it('prioritizes due content without losing finite pool safety',()=>{const tasks=selectTasks([{key:'fresh'},{key:'due'}],1,new Set(['due']),()=>.8);expect(tasks[0].key).toBe('due');});
});
describe('reviewed Czech catalogue',()=>{
  it('provides ten contextual tasks for all seven real consonants',()=>{expect(spellingTasks).toHaveLength(70);for(const group of spellingGroupNames)expect(spellingTasks.filter(t=>t.group===group)).toHaveLength(10);for(const t of spellingTasks){expect(t.word[t.gapIndex-1].toLocaleUpperCase('cs')).toBe(t.group);expect(t.prompt.match(/_/g)).toHaveLength(1);expect(t.sentence.match(/\[/g)).toHaveLength(1);expect(isCorrect({...t,id:'x'},t.word[t.gapIndex])).toBe(true);expect(t.explanation.length).toBeGreaterThan(30);expect(t.ruleId).toBeTruthy();}});
  it('keeps meaning pairs and the chosen letter consistent',()=>{for(const [word,answer,context] of [['výr','y','sovy'],['vír','i','proud'],['mýt','y','umývat'],['mít','i','návštěvu'],['výt','y','hlas'],['vít','i','věneček'],['výskat','y','vykřikovat'],['vískat','i','vlasy']]){const task=spellingTasks.find(t=>t.word===word);expect(task,word).toBeDefined();expect(task!.expected[0]).toBe(answer);expect((task!.explanation+' '+task!.sentence).toLocaleLowerCase('cs')).toContain(context);}});
  it('never removes accents from š or ž to create another target',()=>{expect(spellingTasks.every(t=>!['š','ž'].includes(t.word[t.gapIndex-1].toLocaleLowerCase('cs')))).toBe(true);});
});
describe('personal dictionary preservation and answer variants',()=>{
  it('retains every original personal ID beside the school set',()=>{const words=dictionaryWords({});expect(personalWords).toHaveLength(120);expect(schoolWords).toHaveLength(106);expect(words).toHaveLength(226);expect(new Set(words.map(w=>w.id)).size).toBe(226);const override={...personalWords[0],czech:'Nový překlad',accepted:['Nový překlad']};const edited=dictionaryWords({[override.id]:override});expect(edited).toHaveLength(226);expect(edited.find(w=>w.id===override.id).czech).toBe('Nový překlad');});
  it('accepts declared variants with case and whitespace normalization',()=>{const task={...englishTask({...personalWords[0],english:'evaluate',czech:'posoudit; zhodnotit',accepted:['posoudit','zhodnotit']},'en_to_cz'),id:'x'};expect(isCorrect(task,'  ZHODNOTIT  ')).toBe(true);expect(isCorrect(task,'něco jiného')).toBe(false);expect(personalWords.find(w=>w.english==='refund')?.accepted).toContain('vrátit peníze');});
  it('round-trips commas, quotes, newlines and formula-looking text in CSV',()=>{const words=[{...personalWords[0],english:'"hello", world\nnext',czech:'=1+1'}];expect(parseDictionaryCsv(dictionaryCsv(words))).toEqual([{english:words[0].english,czech:words[0].czech}]);expect(()=>parseDictionaryCsv('"unfinished')).toThrow();});
});
describe('lesson lifecycle',()=>{
  it('accepts only one answer before the explicit next step',()=>{const original=make();const once=answer(original);expect(answer(once)).toBe(once);expect(once.attempts).toHaveLength(1);expect(once.index).toBe(0);expect(reduceLesson(once,{type:'next',at}).index).toBe(1);});
  it('keeps a failed first attempt distinct from a supported correction',()=>{let s=answer(make(),'99');s=reduceLesson(s,{type:'retry'});s=answer(s);expect(s.attempts.map(a=>[a.isCorrect,a.usedHint,a.number])).toEqual([[false,false,1],[true,true,2]]);expect(summarize(s).independent).toBe(0);expect(summarize(s).corrected).toBe(1);});
  it('rejects submit while paused, resumes feedback and freezes ended lessons',()=>{const original=answer(make());const paused=reduceLesson(original,{type:'pause'});expect(answer(paused)).toBe(paused);expect(reduceLesson(paused,{type:'resume'}).phase).toBe('feedback');const ended=reduceLesson(paused,{type:'finish',at});expect(ended.status).toBe('interrupted');expect(answer(ended)).toBe(ended);});
  it('includes the last answer in an exact five-task summary',()=>{const s=complete();expect(s.attempts).toHaveLength(5);expect(summarize(s)).toMatchObject({answered:5,independent:5,corrected:0,firstAccuracy:100});expect(s.status).toBe('completed');});
  it('hides card answers until reveal and records self assessment',()=>{const card:LessonSession={...make(1),subject:'english',mode:'cards',tasks:[{...englishTask(schoolWords[0],'en_to_cz'),id:'card'}]};expect(answer(card)).toBe(card);const revealed=reduceLesson(card,{type:'reveal'});const known=reduceLesson(revealed,{type:'answer',answer:'Vím',id:'known',at,selfCorrect:true});expect(known.attempts[0].assessment).toBe('self');expect(lessonXp({...known,status:'interrupted',completedAt:at},[])).toBe(3);});
  it('does not accept a numeric prefix or decimal as a whole-number answer',()=>{const task=make(1).tasks[0];expect(isCorrect(task,'2abc')).toBe(false);expect(isCorrect(task,'2.0')).toBe(false);expect(isCorrect(task,' 02 ')).toBe(true);});
});
describe('rewards, local dates and persisted data',()=>{
  beforeEach(()=>localStorage.clear());
  it('starts level progress at zero and uses cumulative SQL thresholds',()=>{for(const [xp,level,percent] of [[0,1,0],[125,1,50],[250,2,0],[400,3,0],[550,4,0]])expect(levelProgress(xp)).toMatchObject({level,percent});});
  it('caps daily repeats and awards no XP for wrong answers alone',()=>{const s=complete();expect(lessonXp(s,[])).toBe(55);const second={...s,id:'second'};expect(lessonXp(second,[s])).toBe(5);expect(lessonXp({...second,id:'third'},[s,second])).toBe(0);const wrong={...s,attempts:s.attempts.map(a=>({...a,isCorrect:false}))};expect(lessonXp(wrong,[])).toBe(0);expect(newBadges(wrong,[],{})).toEqual([]);expect(newBadges(s,[],{'first-lesson':at})).not.toContain('first-lesson');});
  it('uses the Prague calendar across midnight and DST',()=>{expect(calendarDay('2026-10-03T22:30:00Z')).toBe('2026-10-04');expect(calendarDay('2026-03-29T22:30:00Z')).toBe('2026-03-30');expect(calendarDay('2026-10-25T23:30:00Z')).toBe('2026-10-26');const s=complete();expect(streak([{...s,activityDate:'2026-10-03'},{...s,id:'b',activityDate:'2026-10-04'}],'2026-10-04')).toBe(2);expect(streak([{...s,activityDate:'2026-10-02'}],'2026-10-04')).toBe(0);});
  it('rebuilds reviews in chronological order without doubling on hydration',()=>{const first=complete();const next={...first,id:'next',completedAt:'2026-10-05T10:00:00Z'};expect(rebuildReviews([next,first])).toEqual(rebuildReviews([first,next]));expect(rebuildReviews([next,first])[first.tasks[0].key].successes).toBe(2);});
  it('isolates profiles, retains damaged storage and merges remote sessions by ID',()=>{const a=storageKey('gabi',false),b=storageKey('misa',false);localStorage.setItem(a,'damaged');expect(readLearningData(a).error).toBeTruthy();expect(localStorage.getItem(a)).toBe('damaged');expect(readLearningData(b).data.sessions).toEqual([]);const s=complete();expect(mergeSessions([s],[s])).toHaveLength(1);expect(mergeSessions([s],[s])[0].sync).toBe('synced');expect(parseLearningData(JSON.stringify({...emptyLearningData(),sessions:[s]})).sessions).toHaveLength(1);expect(()=>parseLearningData('{"version":2,"sessions":[{}],"words":{}}')).toThrow();});
});
