import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, ArrowRight, Pause, Lightbulb, Check, RotateCcw, Volume2 } from 'lucide-react';
import { useLearning } from './context';
import { mathPool, operationLabel, selectTasks } from './math';
import { spellingGroupNames, spellingTasks } from './spelling';
import { dictionaryWords, englishTask, filterWords } from './dictionary';
import { summarize } from './session';
import { subjects } from './catalog';
import { useAuth } from '@/hooks/useAuth';
import { useFamily } from './family-context';
import type { LessonSession, Operation, Preferences, Source, Subject, Task } from './types';

const now = () => new Date().toISOString();
const uuid = () => crypto.randomUUID();

function PauseDialog({ session }: { session: LessonSession }) {
  const dialog = useRef<HTMLDialogElement>(null); const { dispatch } = useLearning();
  useEffect(() => { dialog.current?.showModal(); }, []);
  return <dialog className="learn-dialog" ref={dialog} onCancel={event => { event.preventDefault(); dispatch(session.id,{type:'resume'}); }} aria-labelledby="pause-title"><h2 id="pause-title">Chvilka na oddech.</h2><p>Lekce je uložená na tomto zařízení. Můžeš pokračovat teď nebo se k ní vrátit později.</p><div className="learn-stack"><button className="learn-button primary" autoFocus onClick={()=>dispatch(session.id,{type:'resume'})}>Pokračovat v lekci</button><Link className="learn-button secondary" to="/">Vrátit se domů</Link><button className="learn-text-button" onClick={()=>dispatch(session.id,{type:'finish',at:now()})}>Ukončit a zobrazit výsledky</button></div></dialog>;
}

export default function Practice({ subject }: { subject: Subject }) {
  const { authState } = useAuth();
  const family = useFamily();
  const { data, learnerId, cloud, start, dispatch, savePreferences } = useLearning();
  const meta = subjects.find(s=>s.id===subject)!;
  const [selectedId,setSelectedId] = useState<string | null>(null);
  const session = data.sessions.find(s=>s.id===selectedId) || data.sessions.find(s=>s.subject===subject&&s.status==='active');
  const sessionId=session?.id;
  useEffect(() => { if(sessionId && selectedId!==sessionId) setSelectedId(sessionId); },[sessionId,selectedId]);
  const [draft,setDraft] = useState<Preferences>(()=>({ ...data.preferences, math: { ...data.preferences.math, operations: [...data.preferences.math.operations] }, groups: [...data.preferences.groups], englishSource: data.preferences.englishSource || (family.active?.kind==='child'||(!family.active&&(['gabi','misa','ada'].includes(learnerId) || (authState.profile?.role==='child'&&learnerId!=='host')))?'school':'personal') }));
  const [error,setError] = useState(''); const [answer,setAnswer] = useState(''); const [speechMessage,setSpeechMessage] = useState('');
  const input = useRef<HTMLInputElement>(null); const nextButton = useRef<HTMLButtonElement>(null); const heading = useRef<HTMLHeadingElement>(null); const firstChoice = useRef<HTMLButtonElement>(null);
  const words = useMemo(()=>dictionaryWords(data.words),[data.words]);
  const categories = [...new Set(filterWords(words,draft.englishSource).map(w=>w.category))];
  const available = filterWords(words,draft.englishSource,draft.englishCategory);
  useEffect(()=> { setAnswer(''); if (session?.phase==='answering'&&session.subject!=='spelling'&&session.mode==='typing') input.current?.focus(); if(session?.phase==='answering'&&(session.subject==='spelling'||session.mode==='cards')) firstChoice.current?.focus(); if(session?.phase==='feedback') nextButton.current?.focus(); if(session?.phase==='summary') heading.current?.focus(); },[session?.id,session?.index,session?.phase,session?.mode,session?.subject,session?.revealed]);
  useEffect(()=>()=> { if('speechSynthesis' in window) window.speechSynthesis.cancel(); },[]);
  const begin = (reviewOnly = false) => {
    try {
      if(subject==='spelling'&&!draft.groups.length) throw new Error('Vyber alespoň jednu skupinu vyjmenovaných slov.');
      let pool: Omit<Task,'id'>[] = subject==='math'?mathPool(draft.math):subject==='spelling'?spellingTasks.filter(t=>draft.groups.includes(t.group)):available.map(w=>englishTask(w,draft.englishDirection));
      const priority = new Set(Object.values(data.reviews).filter(r=>r.subject===subject&&r.dueAt<=now()).map(r=>r.key));
      if(reviewOnly) { const reviewKeys = new Set(session ? summarize(session).review.map(r=>r.task.key) : []); pool=pool.filter(t=>reviewKeys.has(t.key)); }
      const tasks = selectTasks(pool,draft.count,priority).map(task=>({...task,id:uuid()})) as Task[];
      const id=uuid();
      const title=subject==='math'?`Matematika · ${draft.math.operations.map(o=>operationLabel[o]).join(' ')}${draft.math.operations.every(o=>o==='+'||o==='-')?` do ${draft.math.max}`:` · násobilka ${draft.math.factorMin}–${draft.math.factorMax}`}`:subject==='spelling'?`Čeština · ${draft.groups.join(', ')}`:`Angličtina · ${draft.englishSource==='school'?'Školní slovíčka':draft.englishSource==='personal'?'Můj slovník':'Všechna slovíčka'}`;
      start({ id, learnerId, subject, contentVersion: 'learning-v2', title, mode:subject==='english'?draft.englishMode:'typing', tasks, attempts:[], index:0, phase:'answering', revealed:false, usedHint:false, status:'active', startedAt:now(), xp:0, sync:cloud?'pending':'local' });
      savePreferences(draft); setSelectedId(id); setError('');
    } catch(error) { setError(error instanceof Error?error.message:'Lekci se nepodařilo připravit.'); }
  };
  const submit = (event?: FormEvent, value = answer, selfCorrect?: boolean) => { event?.preventDefault(); if(session)dispatch(session.id,{type:'answer',answer:value,id:uuid(),at:now(),selfCorrect}); };
  const speak = (text: string) => {
    if(!('speechSynthesis' in window)) {setSpeechMessage('Výslovnost tento prohlížeč nepodporuje.');return;}
    window.speechSynthesis.cancel(); const utterance=new SpeechSynthesisUtterance(text); utterance.lang='en-GB'; utterance.rate=0.85; utterance.onerror=()=>setSpeechMessage('Výslovnost teď není dostupná.'); window.speechSynthesis.speak(utterance);
  };
  if(!session) return <>
    <Link className="learn-back" to="/practice"><ArrowLeft size={18}/> Všechny předměty</Link><div className="learn-page-heading"><div><p className="learn-eyebrow">Připrav si svou lekci</p><h1>{meta.title}</h1><p>{subject==='math'?'Začni lehčím rozsahem a postupně přidávej.':subject==='spelling'?'Doplňuj i/y ve větách, které vysvětlují význam slova.':'Vyber slovíčka a způsob procvičování.'}</p></div>{subject==='english'&&<Link className="learn-button secondary" to="/dictionary/manage">Spravovat slovník</Link>}</div>
    <form className="learn-setup" onSubmit={event=>{event.preventDefault();begin();}}>
      <section className="learn-panel">
        {subject==='math'&&<><h2>Co budeme počítat?</h2><fieldset className="learn-chips"><legend>Početní operace</legend>{(['+','-','*','/'] as Operation[]).map(op=><button type="button" key={op} className={draft.math.operations.includes(op)?'selected':''} aria-pressed={draft.math.operations.includes(op)} onClick={()=>setDraft(p=>({...p,math:{...p.math,operations:p.math.operations.includes(op)?p.math.operations.filter(o=>o!==op):[...p.math.operations,op]}}))}>{operationLabel[op]} {({'+':'Sčítání','-':'Odčítání','*':'Násobení','/':'Dělení'}[op])}</button>)}</fieldset><fieldset className="learn-chips"><legend>Rychlé nastavení</legend>{[10,20,100].map(max=><button type="button" key={max} aria-pressed={draft.math.max===max&&draft.math.min===1} className={draft.math.max===max&&draft.math.min===1?'selected':''} onClick={()=>setDraft(p=>({...p,math:{...p.math,min:1,max}}))}>Do {max}</button>)}</fieldset><details className="learn-details"><summary>Vlastní rozsah</summary><div className="learn-form-grid">{([{key:'min',label:'Nejmenší sčítanec / číslo',max:100},{key:'max',label:'Nejvyšší součet / číslo',max:100},{key:'factorMin',label:'Nejmenší číslo v násobilce',max:12},{key:'factorMax',label:'Největší číslo v násobilce',max:12}] as const).map(field=><label key={field.key}>{field.label}<input type="number" min="0" max={field.max} required value={Number.isNaN(draft.math[field.key])?'':draft.math[field.key]} onChange={e=>setDraft(p=>({...p,math:{...p.math,[field.key]:e.target.value===''?NaN:Number(e.target.value)}}))}/></label>)}</div><p>Sčítání nepřekročí zvolený součet. Odčítání zůstává nezáporné. Dělení má vždy celočíselný výsledek a nenulového dělitele.</p></details><p className="learn-muted">Sčítání a odčítání: do {draft.math.max}. Násobení a dělení: čísla násobilky {draft.math.factorMin}–{draft.math.factorMax}.</p></>}
        {subject==='spelling'&&<><h2>Vyjmenovaná slova a jejich význam</h2><fieldset className="learn-chips"><legend>Vyber skupiny</legend>{spellingGroupNames.map(group=><button type="button" key={group} className={draft.groups.includes(group)?'selected':''} aria-pressed={draft.groups.includes(group)} onClick={()=>setDraft(p=>({...p,groups:p.groups.includes(group)?p.groups.filter(g=>g!==group):[...p.groups,group]}))}>Po {group}</button>)}</fieldset><button type="button" className="learn-text-button" onClick={()=>setDraft(p=>({...p,groups:[...spellingGroupNames]}))}>Vybrat všechny skupiny</button><p className="learn-muted">V každé větě je jedna cílová mezera. Vyjmenované slovo poznáváme podle významu, ne jen podle podoby.</p></>}
        {subject==='english'&&<><h2>Tvoje slovíčka</h2><fieldset className="learn-chips"><legend>Sada slovíček</legend>{([{id:'personal',label:'Můj slovník'},{id:'school',label:'Školní slovíčka'},{id:'all',label:'Všechna slovíčka'}] as {id:Source;label:string}[]).map(source=><button type="button" key={source.id} className={draft.englishSource===source.id?'selected':''} aria-pressed={draft.englishSource===source.id} onClick={()=>setDraft(p=>({...p,englishSource:source.id,englishCategory:'all'}))}>{source.label} <span>{filterWords(words,source.id).length}</span></button>)}</fieldset><div className="learn-form-grid"><label>Okruh<select value={draft.englishCategory} onChange={e=>setDraft(p=>({...p,englishCategory:e.target.value}))}><option value="all">Všechny okruhy</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Směr překladu<select value={draft.englishDirection} onChange={e=>setDraft(p=>({...p,englishDirection:e.target.value as Preferences['englishDirection']}))}><option value="en_to_cz">Angličtina → čeština</option><option value="cz_to_en">Čeština → angličtina</option></select></label></div><fieldset className="learn-chips"><legend>Způsob procvičování</legend><button type="button" className={draft.englishMode==='cards'?'selected':''} aria-pressed={draft.englishMode==='cards'} onClick={()=>setDraft(p=>({...p,englishMode:'cards'}))}>Kartičky · Vím / Učím se</button><button type="button" className={draft.englishMode==='typing'?'selected':''} aria-pressed={draft.englishMode==='typing'} onClick={()=>setDraft(p=>({...p,englishMode:'typing'}))}>Napsat překlad</button></fieldset><p className="learn-muted">{available.length} slovíček ve vybrané sadě. {draft.englishMode==='cards'?'Nejdřív si překlad vybav, potom otoč kartičku. Výsledek hodnotíš sám/sama.':'Přijímáme varianty překladů uvedené ve slovníku.'}</p></>}
      </section><aside className="learn-panel lesson-options"><h2>Malá lekce, tvoje tempo</h2><fieldset className="learn-chips"><legend>Počet úloh</legend>{([5,10,15,20] as const).map(count=><button type="button" key={count} className={draft.count===count?'selected':''} aria-pressed={draft.count===count} onClick={()=>setDraft(p=>({...p,count}))}>{count}</button>)}</fieldset><p>Bez časového limitu. S nápovědou a vysvětlením po každé odpovědi.</p><div className="learn-tip compact">Nastavení se uloží při spuštění lekce.</div>{error&&<p className="learn-error" role="alert">{error}</p>}<button className="learn-button primary" type="submit">Začít lekci <ArrowRight size={19}/></button></aside>
    </form>
  </>;
  if(session.phase==='summary') {
    const summary=summarize(session);
    return <section className="learn-summary"><span className="summary-mark"><Check size={34}/></span><p className="learn-eyebrow">{session.status==='completed'?'Lekce dokončena':'Každý pokus má smysl'}</p><h1 ref={heading} tabIndex={-1}>{summary.answered?'Dobrý krok dopředu.':'Vrátíme se k tomu později.'}</h1><p>{session.title}</p><div className="learn-stat-grid"><div><strong>{summary.independent} / {summary.answered}</strong><span>Napoprvé bez nápovědy</span></div><div><strong>{summary.corrected}</strong><span>Opravených chyb</span></div><div><strong>+{session.xp}</strong><span>XP za procvičování</span></div></div>{session.mode==='cards'&&<p className="learn-muted">Kartičky ukazují tvé vlastní hodnocení znalosti.</p>}{summary.review.length>0&&<div className="learn-panel"><h2>K čemu se vrátíme</h2>{summary.review.map(({task},index)=><p key={task.id}>{index+1}. {task.explanation}</p>)}</div>}<div className="learn-actions">{summary.review.length>0&&<button className="learn-button primary" onClick={()=>begin(true)}><RotateCcw size={19}/> Zopakovat obtížné úlohy</button>}<button className="learn-button secondary" onClick={()=>setSelectedId(null)}>Vybrat další lekci</button><Link className="learn-button secondary" to="/statistiky">Můj pokrok</Link></div>{error&&<p role="alert">{error}</p>}<Link className="learn-back" to="/">Zpět domů</Link></section>;
  }
  const task=session.tasks[session.index]; const last=session.attempts.filter(a=>a.taskId===task.id).at(-1); const feedback=session.phase==='feedback';
  const currentEnglish=task.subject==='english'?task:undefined;
  return <section className="learn-lesson"><div className="lesson-top"><span className="learn-brand small">procvička<span> / {meta.title}</span></span><button className="learn-button secondary" onClick={()=>dispatch(session.id,{type:'pause'})}><Pause size={18}/> Pauza</button></div><div className="lesson-progress"><span>Úloha {session.index+1} z {session.tasks.length}</span><progress value={session.index} max={session.tasks.length} aria-label="Dokončené úlohy"/></div><div className="learn-task" data-subject={subject}><p className="learn-eyebrow">{subject==='math'?'Vypočítej výsledek':subject==='spelling'?`Doplň i nebo y · po ${task.subject==='spelling'?task.group:''}`:currentEnglish?.direction==='en_to_cz'?'Jak se to řekne česky?':'Jak se to řekne anglicky?'}</p><h1 className={subject==='spelling'?'spelling-prompt':'task-prompt'}>{task.prompt}{subject==='math'&&' = ?'}</h1>{currentEnglish?.direction==='en_to_cz'&&<button className="learn-text-button" onClick={()=>speak(currentEnglish.word.english)}><Volume2 size={19}/> Poslechnout výslovnost</button>}{speechMessage&&<p role="status">{speechMessage}</p>}
    {session.mode==='cards'?<div className="learn-card-answer">{!session.revealed?<button ref={firstChoice} className="learn-button primary" onClick={()=>dispatch(session.id,{type:'reveal'})}>Ukázat překlad</button>:<><p className="card-translation">{task.subject==='english'&&task.direction==='cz_to_en'?task.word.english:task.subject==='english'?task.word.czech:task.expected[0]}</p>{currentEnglish?.word.exampleEn&&<p>{currentEnglish.word.exampleEn}<br/><span className="learn-muted">{currentEnglish.word.exampleCz}</span></p>}<div className="learn-actions"><button ref={firstChoice} disabled={feedback} className="learn-button primary" onClick={()=>submit(undefined,task.expected[0],true)}><Check size={20}/> Vím</button><button disabled={feedback} className="learn-button secondary" onClick={()=>submit(undefined,'Nevím',false)}>Ještě se učím</button></div></>}</div>:subject==='spelling'?<div className="spelling-answers"><button ref={firstChoice} className="learn-letter" disabled={feedback} onClick={()=>submit(undefined,'i')}>i / í</button><button className="learn-letter" disabled={feedback} onClick={()=>submit(undefined,'y')}>y / ý</button></div>:<form onSubmit={submit} className="learn-answer-form"><label className="sr-only" htmlFor="lesson-answer">{subject==='math'?'Výsledek':'Tvůj překlad'}</label><input id="lesson-answer" ref={input} value={answer} onChange={e=>setAnswer(e.target.value)} autoComplete="off" autoCapitalize="none" spellCheck={false} inputMode={subject==='math'?'numeric':'text'} pattern={subject==='math'?'[0-9]+':undefined} disabled={feedback} placeholder={subject==='math'?'Výsledek':'Napiš překlad'} required maxLength={200}/><button className="learn-button primary" disabled={feedback||!answer.trim()} type="submit">Zkontrolovat <ArrowRight size={19}/></button></form>}
    {!feedback&&session.mode!=='cards'&&<button className="learn-text-button hint-button" onClick={()=>dispatch(session.id,{type:'hint'})}><Lightbulb size={19}/> Potřebuji nápovědu</button>}{session.usedHint&&!feedback&&<div className="learn-hint" role="status">{task.hint}</div>}
    {feedback&&<div className={`learn-feedback ${last?.isCorrect?'correct':'retry'}`} role="status"><h2>{last?.isCorrect?session.usedHint?'Správně s pomocí.':'Správně!':session.mode==='cards'?'Vrátíme se k tomu.':'Zkusíme to společně.'}</h2>{!last?.isCorrect&&session.mode!=='cards'&&<p>Tvoje odpověď: <strong>{last?.answer}</strong></p>}<p>{task.explanation}</p><div className="learn-actions">{!last?.isCorrect&&session.mode!=='cards'&&<button className="learn-button secondary" onClick={()=>dispatch(session.id,{type:'retry'})}><RotateCcw size={18}/> Zkusit znovu</button>}<button ref={nextButton} className="learn-button primary" onClick={()=>dispatch(session.id,{type:'next',at:now()})}>{session.index+1===session.tasks.length?'Zobrazit výsledky':'Další úloha'}<ArrowRight size={18}/></button></div></div>}
  </div>{session.phase==='paused'&&<PauseDialog session={session}/>}</section>;
}




