-- Remove existing system dictionary words and insert the exact provided list
BEGIN;

DELETE FROM public.dictionary_words WHERE user_id = 'system';

INSERT INTO public.dictionary_words (english_word, czech_translation, difficulty_level, user_id, is_user_created) VALUES
('antidote','protijed','basic','system',false),
('remote','dálkový','basic','system',false),
('dust','prach','basic','system',false),
('evaluate','posoudit','basic','system',false),
('failure','selhání, neúspěch','basic','system',false),
('recover','zotavit se','basic','system',false),
('effectively','účinně','basic','system',false),
('efficiently','výkonně','basic','system',false),
('capabilities','možnosti','basic','system',false),
('sustaining','udržení','basic','system',false),
('thick','tlustý','basic','system',false),
('brush','kartáč','basic','system',false),
('daying','umírat','basic','system',false),
('suddenly','najednou','basic','system',false),
('shaft','šachta','basic','system',false),
('ashamed','zahanbený','basic','system',false),
('atrocity','ukrutnost','basic','system',false),
('strange','zvláštní','basic','system',false),
('honor','čest','basic','system',false),
('tempation','pokušení','basic','system',false),
('lust','chtíč','basic','system',false),
('clarity','jasnost','basic','system',false),
('desire','touha','basic','system',false),
('barely','sotva','basic','system',false),
('rely on','počítat (s něčím)','basic','system',false),
('appears','zobrazí se','basic','system',false),
('bring about','způsobit','basic','system',false),
('towards','vůči, k','basic','system',false),
('observed','pozorovány','basic','system',false),
('upset','smutný','basic','system',false),
('maintain','udržovat','basic','system',false),
('appreciate','vážit si','basic','system',false),
('ordinary','obyčejný','basic','system',false),
('ought to','by měl','basic','system',false),
('jail','vězení','basic','system',false),
('conclusion','závěr','basic','system',false),
('clue','vodítko, legenda','basic','system',false),
('assumption','předpoklad','basic','system',false),
('plants','rostliny','basic','system',false),
('refund','nahradit','basic','system',false),
('exaggerate','přehánět','basic','system',false),
('punctual','dochvilný','basic','system',false),
('loudly','hlasitě','basic','system',false),
('effort','úsilý','basic','system',false),
('buds','buňky','basic','system',false),
('whether','zda','basic','system',false),
('bumps','kůže','basic','system',false),
('consequently','v důsledku','basic','system',false),
('assambled','montovat','basic','system',false),
('punched','děrované','basic','system',false),
('engagement','závazek','basic','system',false),
('addict','závislost','basic','system',false),
('grip','uchopit','basic','system',false),
('roughly','přibližně','basic','system',false),
('crave','toužit (po čem)','basic','system',false),
('subtle','small detail','basic','system',false),
('rare','vyjímečný','basic','system',false),
('regret','politování','basic','system',false),
('confession','doznání','basic','system',false),
('eventuality','enentuality','basic','system',false),
('survive','přežít','basic','system',false),
('in addition','navíc','basic','system',false),
('already','již','basic','system',false),
('considerably','značně','basic','system',false),
('accomplished','vynikající','basic','system',false),
('accomplish','dosáhnout','basic','system',false),
('plunge','průdký pokles','basic','system',false),
('affirmative','kladný','basic','system',false),
('claim','prohlašovat, tvrdit','basic','system',false),
('emphasize','zdůraznovat','basic','system',false),
('affair','záležitost','basic','system',false),
('conduct','chování','basic','system',false),
('recognize','uznat, být si vědom','basic','system',false),
('accuse','obvinit','basic','system',false),
('expose','odhalit','basic','system',false),
('fair','trh','basic','system',false),
('dare','odvážit se','basic','system',false),
('gossip','tlachat','basic','system',false),
('harmful','škodlivý','basic','system',false),
('purpouse','záměr','basic','system',false),
('pursuit','pronásledování','basic','system',false),
('gear','výbava','basic','system',false),
('incredibly','neuvěřitelný','basic','system',false),
('tailored','na míru','basic','system',false),
('appropiate','odpovídající','basic','system',false),
('favour','upřednostňuje','basic','system',false),
('convenient','vhodný','basic','system',false),
('accompaniment','doprovod','basic','system',false),
('twitchy','nervózní','basic','system',false),
('weird','podivný','basic','system',false),
('stuff','věc','basic','system',false),
('struggle','boj','basic','system',false),
('brim','okraj','basic','system',false),
('regarding','týkající se','basic','system',false),
('therby','čímž','basic','system',false),
('whereas','zatímco','basic','system',false),
('burrows','nory','basic','system',false),
('tuxedos','smoking','basic','system',false),
('ingnisitive','zvědavý','basic','system',false),
('curious','zvědavý','basic','system',false),
('pollution','zněčištěný','basic','system',false),
('significance','významný','basic','system',false),
('dozen','tucet','basic','system',false),
('astonishingly','kupodivu','basic','system',false),
('suffer','trpět','basic','system',false),
('cope','vypořádat se','basic','system',false),
('handle','zvládnout','basic','system',false),
('justify','odůvodnit','basic','system',false),
('peak','vrchol','basic','system',false),
('fulfilled','uspokojení','basic','system',false),
('enrollment','zápis','basic','system',false),
('diverse','rozmanitý','basic','system',false),
('whenever','kdykoli','basic','system',false),
('accuratly','přesně','basic','system',false),
('adjust','nastavit','basic','system',false),
('manoeuvre','manévrovat','basic','system',false),
('straw','brčko','basic','system',false),
('reverse','opak','basic','system',false),
('accused','obvinit','basic','system',false),
('extraterrestrial','mimozemský','basic','system',false);

COMMIT;