
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arnowuvckpxpeavrcbri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFybm93dXZja3B4cGVhdnJjYnJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MDczMzgsImV4cCI6MjA2NDA4MzMzOH0.675zuWau_IF2zUgU0_XxpgeUW8eUipZL4IGjMrOGoG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Function to check Supabase connection
export const checkSupabaseConnection = async () => {
  const startTime = Date.now();
  
  try {
    // Try a simple query to check if the connection works
    // Since there are no tables yet, we'll just test the connection with a simple query
    const { error } = await supabase.rpc('now');
    const elapsed = Date.now() - startTime;
    
    if (error && error.message?.includes('function now() does not exist')) {
      // This means we connected but there's no function, which is expected
      return {
        success: true,
        elapsed,
        message: "Connection successful (no tables yet)"
      };
    }
    
    if (error) {
      return {
        success: false,
        error,
        elapsed
      };
    }
    
    return {
      success: true,
      elapsed
    };
  } catch (error) {
    const elapsed = Date.now() - startTime;
    
    // Check if it's a network error
    if (error instanceof TypeError && error.message.includes('fetch')) {
      return {
        success: false,
        error: { message: 'Network error - check internet connection' },
        elapsed,
        offline: true
      };
    }
    
    // Check for timeout
    if (elapsed > 10000) {
      return {
        success: false,
        error: { message: 'Connection timeout' },
        elapsed,
        timeout: true
      };
    }
    
    return {
      success: false,
      error: { message: error?.toString() || 'Unknown error' },
      elapsed
    };
  }
};
