// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arnowuvckpxpeavrcbri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFybm93dXZja3B4cGVhdnJjYnJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MDczMzgsImV4cCI6MjA2NDA4MzMzOH0.675zuWau_IF2zUgU0_XxpgeUW8eUipZL4IGjMrOGoG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);